# Generated by Django 5.1 on 2025-10-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("TEACHER", "Teacher"),
                    ("ADMIN", "Admin"),
                ],
                default="STUDENT",
                max_length=10,
            ),
        ),
    ]
