# Generated by Django 5.1 on 2025-11-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manage", "0003_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subject",
            old_name="course",
            new_name="course_id",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="semester",
            new_name="semester_id",
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("course_id", "code", "semester_id")},
        ),
    ]
